-- MySQL Script generated by MySQL Workbench
-- Sun Jan 15 13:03:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `foto` LONGTEXT NULL,
  `nombre` VARCHAR(15) NULL,
  `apellido` VARCHAR(20) NULL,
  `titulo` TIMESTAMP NULL,
  `sobre_mi` LONGTEXT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `mydb`.`estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logo` LONGTEXT NULL,
  `institucion` VARCHAR(45) NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `detalles` LONGTEXT NULL,
  `duracion` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_estudio_usuario3_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_estudio_usuario3`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`experiencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logo` LONGTEXT NULL,
  `institucion` VARCHAR(50) NULL,
  `puesto` VARCHAR(45) NULL,
  `duracion` VARCHAR(25) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_experiencia_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_experiencia_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logo` LONGTEXT NULL,
  `institucion` VARCHAR(45) NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `detalles` LONGTEXT NULL,
  `duracion` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_estudio_usuario3_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_estudio_usuario3`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logo` LONGTEXT NULL,
  `institucion` VARCHAR(45) NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `detalles` LONGTEXT NULL,
  `duracion` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_estudio_usuario3_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_estudio_usuario3`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logo` LONGTEXT NULL,
  `institucion` VARCHAR(45) NULL,
  `titulo` VARCHAR(255) NOT NULL,
  `detalles` LONGTEXT NULL,
  `duracion` VARCHAR(45) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_estudio_usuario3_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_estudio_usuario3`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`habilidad` (
  `id` INT NOT NULL,
  `porcentaje` INT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_habilidad_usuario4_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_habilidad_usuario4`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`habilidad` (
  `id` INT NOT NULL,
  `porcentaje` INT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_habilidad_usuario4_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_habilidad_usuario4`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`habilidad` (
  `id` INT NOT NULL,
  `porcentaje` INT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_habilidad_usuario4_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_habilidad_usuario4`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`habilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`habilidad` (
  `id` INT NOT NULL,
  `porcentaje` INT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_habilidad_usuario4_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_habilidad_usuario4`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyecto` (
  `id` INT NOT NULL,
  `logo` LONGTEXT NULL,
  `proyecto` VARCHAR(45) NULL,
  `descripcion` MEDIUMTEXT NULL,
  `fecha` MEDIUMTEXT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_proyecto_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_proyecto_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
